version: "3.4"

services:
  react-frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: react_build
    environment:
      - NODE_ENV=development
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
